### ISSUE TITLE
Can not support skip Embedded Field?

### ISSUE THREAD

**Issue by magicianlyx** [reedom/convergen#19]
i want to convert gorm model structure to another structure and skip embedded field 'gorm.Model', but it not work.

ForExample

```
import "gorm.io/gorm"

type ModelResult struct {
	OrderNo string
	UserId  int64
}

type Response struct {
	gorm.Model
	OrderNo string
	UserID  int
}

//go:generate go run github.com/reedom/convergen@v0.6.3
type Convergen interface {
	// :typecast
	// :case:off
	// :skip Model
	WrapLogin(*ModelResult) *Response
}

```

**Comment by reedom** [comment]
@magicianlyx
Don't forget that `convergen` generates outputs in the same directory as the description file in default.
As a result, you got symbol duplication errors.

Those are what I recommend:
- define models in separate files.
- define a Go tag in `convergen` description files.

sample:

models/model.go
```go
package models

import (
	"gorm.io/gorm"
)

type ModelResult struct {
	OrderNo string
	UserId  int64
}

type Response struct {
	gorm.Model
	OrderNo string
	UserID  int
}
```

converter.go
```go
//go:build convergen

package convergen_tests

import (
        // ** It needs to import types when it's necessary **
	"example.com/foobar/sample_project/models"
)

//go:generate go run github.com/reedom/convergen@v0.6.3
type Convergen interface {
	// :typecast
	// :case:off
	// :skip Model
	WrapLogin(result *models.ModelResult) *models.Response
}
```

And we'll get converter.gen.go by
```
% go generate -tags convergen ./...
```

```go
// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package convergen_tests

import (
	"example.com/foobar/sample_project/models"
)

func WrapLogin(result *models.ModelResult) (dst *models.Response) {
	dst = &models.Response{}
	// skip: dst.Model
	dst.OrderNo = result.OrderNo
	dst.UserID = int(result.UserId)

	return
}
```

**Comment by magicianlyx** [comment]
> @magicianlyx Don't forget that `convergen` generates outputs in the same directory as the description file in default. As a result, you got symbol duplication errors.
> 
> Those are what I recommend:
> 
> * define models in separate files.
> * define a Go tag in `convergen` description files.
> 
> sample:
> 
> models/model.go
> 
> ```go
> package models
> 
> import (
> 	"gorm.io/gorm"
> )
> 
> type ModelResult struct {
> 	OrderNo string
> 	UserId  int64
> }
> 
> type Response struct {
> 	gorm.Model
> 	OrderNo string
> 	UserID  int
> }
> ```
> 
> converter.go
> 
> ```go
> //go:build convergen
> 
> package convergen_tests
> 
> import (
>         // ** It needs to import types when it's necessary **
> 	"example.com/foobar/sample_project/models"
> )
> 
> //go:generate go run github.com/reedom/convergen@v0.6.3
> type Convergen interface {
> 	// :typecast
> 	// :case:off
> 	// :skip Model
> 	WrapLogin(result *models.ModelResult) *models.Response
> }
> ```
> 
> And we'll get converter.gen.go by
> 
> ```
> % go generate -tags convergen ./...
> ```
> 
> ```go
> // Code generated by github.com/reedom/convergen
> // DO NOT EDIT.
> 
> package convergen_tests
> 
> import (
> 	"example.com/foobar/sample_project/models"
> )
> 
> func WrapLogin(result *models.ModelResult) (dst *models.Response) {
> 	dst = &models.Response{}
> 	// skip: dst.Model
> 	dst.OrderNo = result.OrderNo
> 	dst.UserID = int(result.UserId)
> 
> 	return
> }
> ```


---

i still can not resolve.

---

next i show some

**project directory tree**

```
/d/Users/magicianlyx/Documents/go/src/test
│  converter.go
│  go.mod
│  go.sum
│
└─models
        model.go


```

**go version**

```
go version go1.22.6 windows/amd64
```


**models/model.go**

```
package models

import "gorm.io/gorm"

type ModelResult struct {
	OrderNo string
	UserId  int64
	gorm.Model
}

type Response struct {
	OrderNo string
	UserID  int
}

```





**converter.go**

```
//go:build convergen

package convergen_tests

import "convergen_tests/models"

//go:generate go run github.com/reedom/convergen@v0.6.3
type Convergen interface {
	// :typecast
	// :case:off
	// :skip Model
	WrapLogin(result *models.ModelResult) *models.Response
}

```


---
** go.mod**

```
module convergen_tests

go 1.22

require (
	gorm.io/gorm v1.25.11
)

require (
	github.com/jinzhu/inflection v1.0.0 // indirect
	github.com/jinzhu/now v1.1.5 // indirect
	golang.org/x/text v0.14.0 // indirect
)
```

---


run bash script  in the  directory `/d/Users/magicianlyx/Documents/go/src/test`

```
go generate -tags convergen ./...
```


---

panic error
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xba130f]

goroutine 103 [running]:
go/types.(*Checker).handleBailout(0xc0004ec000, 0xc0007ffc60)
        C:/Users/magicianlyx/.g/go/src/go/types/check.go:367 +0x88
panic({0xc5fb20?, 0xef3c30?})
        C:/Users/magicianlyx/.g/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xd34f78, 0xef7080})
        C:/Users/magicianlyx/.g/go/src/go/types/sizes.go:228 +0x30f
go/types.(*Config).sizeof(...)
        C:/Users/magicianlyx/.g/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0xd34f78?, 0xef7080?})
        C:/Users/magicianlyx/.g/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xd36260, 0xeec3c0}, 0xc0004ec000, 0xef7080, 0xc0007fd098)
        C:/Users/magicianlyx/.g/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc0004ec000, 0xc0004ffc40, 0xef7080)
        C:/Users/magicianlyx/.g/go/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc0004ec000, 0xc0004ffc40, {0xd34f78, 0xef7080})
        C:/Users/magicianlyx/.g/go/src/go/types/expr.go:375 +0x2d7
go/types.(*Checker).assignment(0xc0004ec000, 0xc0004ffc40, {0xd34f78, 0xef7080}, {0xcbc9f3, 0x10})
        C:/Users/magicianlyx/.g/go/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).initVar(0xc0004ec000, 0xc0002108a0, 0xc0004ffc40, {0xcbc9f3, 0x10})
        C:/Users/magicianlyx/.g/go/src/go/types/assignments.go:163 +0x3b2
go/types.(*Checker).initVars(0xc0004ec000, {0xc0002061a0, 0x1, 0xd34f78?}, {0xc000508110, 0xef7060?, 0xc000210ea0?}, {0xd35a60, 0xc000286840})
        C:/Users/magicianlyx/.g/go/src/go/types/assignments.go:382 +0x638
go/types.(*Checker).stmt(0xc0004ec000, 0x0, {0xd35a60, 0xc000286840})
        C:/Users/magicianlyx/.g/go/src/go/types/stmt.go:524 +0x1fc5
go/types.(*Checker).stmtList(0xc0004ec000, 0x0, {0xc000508120?, 0xca753b?, 0x5?})
        C:/Users/magicianlyx/.g/go/src/go/types/stmt.go:121 +0x85
go/types.(*Checker).stmt(0xc0004ec000, 0x0, {0xd35af0, 0xc000550900})
        C:/Users/magicianlyx/.g/go/src/go/types/stmt.go:562 +0x20f2
go/types.(*Checker).stmt(0xc0004ec000, 0x0, {0xd35b20, 0xc0004fe4c0})
        C:/Users/magicianlyx/.g/go/src/go/types/stmt.go:574 +0x3017
go/types.(*Checker).stmtList(0xc0004ec000, 0x0, {0xc000122000?, 0x0?, 0xc000590798?})
        C:/Users/magicianlyx/.g/go/src/go/types/stmt.go:121 +0x85
go/types.(*Checker).funcBody(0xc0004ec000, 0xd34f78?, {0xc00038a1c0?, 0xef7080?}, 0xc0004ff0c0, 0xc000550a50, {0x0?, 0x0?})
        C:/Users/magicianlyx/.g/go/src/go/types/stmt.go:41 +0x331
go/types.(*Checker).funcDecl.func1()
        C:/Users/magicianlyx/.g/go/src/go/types/decl.go:852 +0x3a
go/types.(*Checker).processDelayed(0xc0004ec000, 0x0)
        C:/Users/magicianlyx/.g/go/src/go/types/check.go:467 +0x162
go/types.(*Checker).checkFiles(0xc0004ec000, {0xc000206008, 0x1, 0x1})
        C:/Users/magicianlyx/.g/go/src/go/types/check.go:411 +0x1cc
go/types.(*Checker).Files(...)
        C:/Users/magicianlyx/.g/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc00016c1c0, 0xc0004dfb80)
        D:/Users/magicianlyx/Documents/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:1001 +0x76f
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        D:/Users/magicianlyx/Documents/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:838 +0x1a9
sync.(*Once).doSlow(0x0?, 0x0?)
        C:/Users/magicianlyx/.g/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        C:/Users/magicianlyx/.g/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        D:/Users/magicianlyx/Documents/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:826 +0x4a
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        D:/Users/magicianlyx/Documents/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:833 +0x26
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 100
        D:/Users/magicianlyx/Documents/go/pkg/mod/golang.org/x/tools@v0.1.12/go/packages/packages.go:832 +0x94
exit status 2
converter.go:7: running "go": exit status 1
```



Is it triggered by the golang version？
what your golang version for build `convergen`

**Comment by magicianlyx** [comment]
I found that it can run normally on version 1.19
can you upgrade it to support 1.22 ?

**Comment by reedom** [comment]
@magicianlyx 
Thanks for reporting, I've rebuilt the tool on Go 1.23.0.
Could you have a try?
```
//go:generate go run github.com/reedom/convergen@v0.7.0
type Convergen interface {
…
```

**Comment by magicianlyx** [comment]
it ok, tks my bro.
